branch-defaults:
  master:
    environment: akaHub-env2
    group_suffix: null
environment-defaults:
  flask-env:
    branch: null
    repository: null
global:
  application_name: myakaHub
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.6
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
